name: Test Release CI

on:
  workflow_dispatch:

jobs:

  windows:
    uses: wxyzh/librime/.github/workflows/windows-build.yml@Buildlibrime
    with:
      repository: rime/librime
      branch: master
      rime_plugins: hchunhui/librime-lua lotem/librime-octagram fxliang/librime-predict-leveldb
      
  macos:
    uses: wxyzh/librime/.github/workflows/macos-build.yml@Buildlibrime
    with:
      repository: rime/librime
      rime_plugins: hchunhui/librime-lua lotem/librime-octagram rime/librime-predict

  release:
    needs: [windows, macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

