name: Test Release CI

on: workflow_dispatch


jobs:
  linux:
    uses: ./.github/workflows/linux-build.yml
    with:
      repository: rime/librime

  macos:
    uses: ./.github/workflows/macos-build.yml
    with:
      build_variant: '-universal'
      rime_plugins: rime/librime-charcode hchunhui/librime-lua lotem/librime-octagram
      repository: rime/librime

  windows:
    uses: ./.github/workflows/windows-build.yml
    with:
      rime_plugins: rime/librime-charcode hchunhui/librime-lua lotem/librime-octagram
      repository: rime/librime

  release:
    needs: [macos, windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

